# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7f2547f8397fa35e738008e39274f7d2be9e3df7ce237c48bbaae13cdaa3a4ee2787a93ae1ee270ba36c154838255be3b32ca612506fcb8cfc53c76fcfdc7c6

test:
  secret_key_base: ace6895881336e3851a628aa9ba082ebdfb0afb415bea5900a53a0aa6a113ae54212a09561e9cf463ee26cbf1383c586b293a4772b914958e9beeb5b1c952909

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
